---
name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pandoc/actions/setup@main
      - run: sudo apt-get install -y npm moreutils
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: cd ${{ github.workspace }}
      - run: npm i
      - run: make -j
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{ github.workspace }}/build"
